import { useDashboard } from './DashboardContext';
import { CATEGORIES_WITH_COUNTS } from '../promptsData';
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';

export const Header = () => {
  const {
    searchQuery,
    setSearchQuery,
    currentCategory,
    setCurrentCategory,
    currentView,
    setCurrentView,
    setSelectedPromptId
  } = useDashboard();

  // List of pills to render
  const pills = [
    { name: null, label: 'All' },
    { name: 'Art', label: 'Art' },
    { name: 'Photography', label: 'Photographs' },
    { name: 'Illustration', label: 'Illustrations' },
    { name: '3D Render', label: '3D Renders' },
    { name: 'UI / UX', label: 'UI / UX' },
    { name: 'Anime', label: 'Anime' },
    { name: 'Sci-Fi', label: 'Sci-Fi' },
    { name: 'Architecture', label: 'Architecture' },
    { name: 'Nature', label: 'Nature' }
  ];

  // Dynamic header title based on current view/category
  const getHeaderTitle = () => {
    if (currentView === 'trending') return 'Trending Prompts';
    if (currentView === 'favorites') return 'My Favorites';
    if (currentView === 'contribute') return 'Submit a Prompt';
    if (currentCategory) return `${currentCategory} Collection`;
    return 'Prompt Collection';
  };

  const getHeaderSubtitle = () => {
    if (currentView === 'trending') return 'The most popular prompts generated by the community.';
    if (currentView === 'favorites') return 'Your curated list of saved prompts.';
    if (currentView === 'contribute') return 'Share your creative prompts with the community.';
    return 'Discover and copy the best prompts for AI art.';
  };

  return (
    <header className="flex flex-col bg-transparent text-[#0F172A] select-none py-6 px-8 gap-6">
      
      {/* Top Row: Title, Subtitle, and Favorites button */}
      <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight text-[#0F172A] leading-none">
            {getHeaderTitle()}
          </h1>
          <p className="text-sm text-[#64748B] mt-2 font-medium">
            {getHeaderSubtitle()}
          </p>
        </div>

        {/* My Favorites Shortcut Button */}
        {currentView !== 'favorites' && (
          <Button
            onClick={() => {
              setCurrentView('favorites');
              setCurrentCategory(null);
              setSelectedPromptId(null);
            }}
            variant="outline"
            size="sm"
            className="flex items-center gap-2 cursor-pointer shadow-sm bg-white"
          >
            <svg className="w-3.5 h-3.5 text-[#64748B] fill-none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
            </svg>
            <span>My Favorites</span>
          </Button>
        )}
      </div>

      {/* Middle Row: Search and Filters */}
      {currentView !== 'contribute' && (
        <div className="flex items-center gap-3">
          {/* Search Input */}
          <div className="relative flex-grow max-w-xl">
            <span className="absolute inset-y-0 left-0 flex items-center pl-3.5 pointer-events-none text-[#64748B] z-10">
              <svg 
                className="w-4 h-4" 
                fill="none" 
                stroke="currentColor" 
                viewBox="0 0 24 24" 
                xmlns="http://www.w3.org/2000/svg"
              >
                <path 
                  strokeLinecap="round" 
                  strokeLinejoin="round" 
                  strokeWidth={2.5} 
                  d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" 
                />
              </svg>
            </span>
            <Input
              placeholder="Search prompts..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10"
            />
            {searchQuery && (
              <button 
                onClick={() => setSearchQuery('')}
                className="absolute inset-y-0 right-0 flex items-center pr-3 text-[#64748B] hover:text-[#0F172A] z-10"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            )}
          </div>

          {/* Filters Settings button */}
          <Button 
            variant="outline"
            className="flex items-center gap-2 cursor-pointer bg-white"
            onClick={() => alert('Filter settings configured in details drawer.')}
          >
            <svg className="w-4 h-4 text-[#64748B]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4" />
            </svg>
            <span>Filters</span>
          </Button>
        </div>
      )}

      {/* Bottom Row: Pill tabs & Sort selection */}
      {currentView === 'browse' && (
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between border-t border-[#E2E8F0] pt-4 gap-4">
          {/* Categories Pills */}
          <div className="flex flex-wrap gap-2">
            {pills.map((pill) => {
              const isActive = currentCategory === pill.name;
              return (
                <Button
                  key={pill.label}
                  onClick={() => setCurrentCategory(pill.name)}
                  variant={isActive ? "default" : "outline"}
                  className={`px-4 py-2 text-xs font-bold rounded-full transition-all duration-150 cursor-pointer ${
                    isActive 
                      ? 'bg-[#6366F1] border-[#6366F1] text-white hover:bg-[#4F46E5] hover:border-[#4F46E5]' 
                      : 'bg-white border-[#E2E8F0] text-[#64748B] hover:text-[#0F172A] hover:border-[#94A3B8]'
                  }`}
                >
                  {pill.label}
                </Button>
              );
            })}
          </div>

          {/* Sort Selection dropdown */}
          <div className="flex items-center gap-2 text-xs font-bold text-[#64748B] cursor-pointer hover:text-[#0F172A] transition-colors self-end sm:self-auto">
            <span>Newest First</span>
            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M19 9l-7 7-7-7" />
            </svg>
          </div>
        </div>
      )}
    </header>
  );
};
